### ISSUE TITLE
docs: fix readme docs

### ISSUE THREAD

**Issue by kaminskypavel** [kaminskypavel/fullpower-stack#10]
the tech table should be migrated from MD to html , and we should consider updating the version numbers automatically 
instead of manually

**Comment by kaminskypavel** [comment]
@vithano since you're on a roll 🛼🛼 mind taking this and creating a more user-friendly readme? 

maybe later on we will create a docs site, but for now, I think a nice readme might be sufficient.


here are some ideas :
https://github.com/vitest-dev/vitest
https://github.com/vitejs/vite
https://github.com/expo/expo
https://github.com/babel/babel

**Comment by kumiiko** [comment]
I'll work on it

**Comment by kaminskypavel** [comment]
> I'll work on it

excellent, consider to collaborate on https://github.com/kaminskypavel/fullpower-stack/pull/14

**Comment by vithano** [comment]
Can be closed

**Comment by kaminskypavel** [comment]
thanks! 🚀🚀
