### ISSUE TITLE
integrate a codesandbox/stackblitz

### ISSUE THREAD

**Issue by kaminskypavel** [kaminskypavel/fullpower-stack#16]
it will be easier to demo and review PRs if we'd have something to preview in the browser

**Comment by kailoon** [comment]
I have it imported here https://codesandbox.io/p/github/kailoon/fullpower-stack/master

**Comment by kailoon** [comment]
@kaminskypavel PR created/ Updated CSB [link](https://codesandbox.io/p/github/kailoon/fullpower-stack/integrate-a-codesandbox?selection=%5B%7B%22endColumn%22%3A33%2C%22endLineNumber%22%3A6%2C%22startColumn%22%3A33%2C%22startLineNumber%22%3A6%7D%5D&workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clb50a8qr009d3b6hoapy8knw%2522%253A%257B%2522key%2522%253A%2522clb50a8qr009d3b6hoapy8knw%2522%252C%2522name%2522%253A%2522Default%2520Space%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clb50aswo00pj3b6hjod6vdis%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clb50apul00kx3b6htxv43y7w%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clb50a8qr009d3b6hoapy8knw%2522%257D)
