### ISSUE TITLE
test: add playwright e2e tests

### ISSUE THREAD

**Issue by kaminskypavel** [kaminskypavel/fullpower-stack#8]

**Comment by kaminskypavel** [comment]
what do we want?
to be able to perform a full e2e test on each commit/PR

when do we want it? now!

jokes, aside I've added the initial playwright test in commit https://github.com/kaminskypavel/fullpower-stack/commit/0b29b572562ac44604dbb4cccf96b025bd2dbf04

but there's a challenge, the frontend is tightly coupled with the backend service. we can mock HTTP calls with fixtures, 
but that would be just pure `frontend` testing, instead, I suggest we do a full "smoke" testing by calling real backend endpoints.
Since our DB is an SQLite instance beneath Prisma this shouldn't be an issue.

here's my dream pipeline :

comit a PR -> CI kicks in -> build and unit testing -> an full e2e kicks in -> Accept PR.

to achieve this there's 3 platform we can explore .

1. codesandbox, we already have some integrations , here is an [example1](https://cy7e2m-5173.preview.csb.app/)  & [exmaple2](https://codesandbox.io/p/github/kaminskypavel/fullpower-stack/master?file=%2Fsandbox.config.json) . from here we need a way to extract the url and pass it to an e2e action
2.  vercel, from a quick google, it looks like it supports both `turborepo` and `express` server. probably will need to explore more.
3. google cloud run  - if we want to do anything from scratch.

**Comment by kaminskypavel** [comment]
by the way, looks there's this product https://developer.stackblitz.com/codeflow/what-is-codeflow

unfortunately we cant use it, since they use `webcontainers` and it clashes with `prisma` since it's not supporting WASM

**Comment by kaminskypavel** [comment]
found this [repo](https://github.com/belgattitude/nextjs-monorepo-example) looks like there are something we can pick up

**Comment by vithano** [comment]
@kaminskypavel that repo works but they dont seem to be deploying it externally , only locally, i kept looking at codesandbox and both them an vercel have a CI app we can integrate to github, i need access to set it up though

**Comment by kaminskypavel** [comment]
Codesandbox is already set. Anyways, I now starting to think that we should investigate on how to spin a docker environment with a `dev:vite` task running , and use playwright to test against it.

Only if the test are successful the pr will be eligible for a merge.
I did send you an example of such project earlier, also turbo has a whole section on how to do a docker multistep build efficiently, one cavet we might consider is there seems to be some extra steps for using `pnpm` inside a docker container, and we cannot use yarn/npm since our lock files are in a pnpm format.

**Comment by kaminskypavel** [comment]
awesome job! 
[closing](https://github.com/kaminskypavel/fullpower-stack/pull/28)
